### ISSUE TITLE
Need tagged trace for "wiener" after DNN ROI finding

### ISSUE THREAD

**Issue by wenqiang-gu** [WireCell/wire-cell-toolkit#345]
We have recently implemented the DNN ROI in ProtoDUNE HD, ex: https://github.com/DUNE/dunereco/blob/57df1196bdb041aa6c1c9c1ac1dcc3081925545a/dunereco/DUNEWireCell/pdhd/wcls-rawdigit-dnnsp.jsonnet#L312

To further integrate the WireCell imaging, we need both tagged traces for "dnnsp" and "wiener", where "dnnsp" is available from DNN ROI Finding. However, "wiener" traces are not saved after DNN ROI.

One possible solution: we could add additional tagged traces when we save the "dnnsp" traces: https://github.com/WireCell/wire-cell-toolkit/blob/fa806dae3682215afb7d7f1ba5c3fa10415b8751/pytorch/src/DNNROIFinding.cxx#L306

**Comment by HaiwangYu** [comment]
Hi Wenqiang,

I made a configuration to fanout the gauss/wiener traces and save to artROOT, something like this:
https://github.com/HaiwangYu/sbnd-dnn-roi/blob/main/wcls-nf-sp-data-dnnroi-save-both.jsonnet
visualization:
https://github.com/HaiwangYu/sbnd-dnn-roi/blob/main/wcls-nf-sp-data-dnnroi-save-both.pdf

It should be a better solution in sense of DFP principal (forwarding only necessary data instead of keep all). But the configuration is quite complicated.

**Comment by wenqiang-gu** [comment]
Yeah, the configuration would be complicated if we add imaging. Perhaps we could split the fhicl job into several jobs.

**Comment by wenqiang-gu** [comment]
@HaiwangYu Okay, it seems easy to adapt your SBND jsonnet and save all frames ("gauss", "wiener", "dnnsp") to artROOT.

**Comment by brettviren** [comment]
Hi @HaiwangYu and @wenqiang-gu 

I know this Issue was closed using good old-fashioned custom coding but it prompted me to write a generic `splice()` function in `pgraph.jsonnet`.

This function lets you take an original graph like this:

![orig](https://github.com/user-attachments/assets/103bbfdb-fd60-48da-9e2d-5ea7eaeed611)

And a subgraph like this:

![out](https://github.com/user-attachments/assets/820aafcf-938e-43de-9a6b-c571fae3cd9c)

(note, our graphviz does not draw things correctly but there are two "open" ports on that leading `Fanin:outfanin`.)

And then "splice" the subgraph into the original graph to make this new graph:

![spliced](https://github.com/user-attachments/assets/a40d9adb-2668-45d4-9ce6-6a240d2e2491)

The caller provides two functions:

- `edge_selector(edge)` to return true if an edge should be "spliced"

- `fanout_factory(number, edge)` returns the configuration object for the correct kind of fanout to insert on the broken `edge` numbered `number`.

This approach could be extended to more arbitrary "splicing".

One caveat: my testing was done with made up nodes so perhaps real use will uncover the need for fixes.

**Comment by wenqiang-gu** [comment]
Hi @brettviren , it looks like the `splice()` function can save some coding. Could you share jsonnet code from your example?  I am curious about how the `edge_selector()` function is define in details.

**Comment by brettviren** [comment]
Hi @wenqiang-gu 

Yes, the test includes examples of both "edge selector" and "fanout factory" functions.  Here is a link to the two functions provided for the "made up" nodes:

https://github.com/WireCell/wire-cell-toolkit/blob/master/cfg/test/test-splice.jsonnet#L54

In general, these two function could become quite complicated depending on how the original graph was made and how one wants to "splice" in the subgraph.  Building the original graph using some some kind of consistent node naming convention can help to allow these functions to stay simple.  Worse case, we may write an "edge selector" which is simply given a list of all edge names (or perhaps tail or head nodes) to match.  And, likewise we may write a "fanout factory" which is an exhaustive map from each broken edge to the fanout to insert.  Both types of "exhaustive" functions could be generic and provided also in `pgraph.jsonnet`.

You can regenerate the PNGs for the initial graph (orig) and subgraph (out) and final "spliced" graph from the test Jsonnet file with commands like:

```
wirecell-pgraph dotify -A what=orig cfg/test/test-splice.jsonnet orig.png
wirecell-pgraph dotify -A what=out cfg/test/test-splice.jsonnet out.png
wirecell-pgraph dotify -A what=spliced cfg/test/test-splice.jsonnet spliced.png
```

**Comment by wenqiang-gu** [comment]
The ProtoDUNE configuration now has been updated with the `splice()` function. See details: https://indico.bnl.gov/event/25449/
